# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    #docker:
      # the Docker image with Cypress dependencies
      #- image: cypress/base:8
           
    working_directory: ~/Angular
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - Angular-{{ checksum "package.json" }}
          
      - run: npm install 
      - save_cache:
          paths:
            - node_modules
          key: Angular-{{ checksum "package.json" }}
                  
      # run tests!
      #- run: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-result

  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/Angular
    steps:
      - checkout
      - save_cache:
          paths:
            - node_modules
          key: Angular-{{ checksum "package.json" }}
      - run:
          name: Install angularcli
          command: |
      - run: sudo npm uninstall -g @angular/cli
      - run: sudo npm cache verify
      - run: sudo npm install -g @angular/cli@next
      - run:
          name: Run unit tests with karma
          command: ng test
                
      - store_test_results:
          path: test-results.xml
          
workflows:
  version: 2
  Build-Test-Deploy:
    jobs:
      - build
      - test:
          requires:
            - build        

